In [3]:
import pandas as pd
import random

templates = {
    'vendas': {
        's': ['', 'Olá', 'Bom dia', 'Gostaria de saber', 'Por favor'],
        'a': ['quero comprar', 'qual o preco do', 'tem cupom para', 'como faco para adquirir', 'desejo orcamento de'],
        'o': ['sofa retratil 3 lugares', 'conjunto de mesa de jantar', 'guarda roupa casal', 'painel para tv', 'colchao queen size']
    },
    'suporte': {
        's': ['', 'Oi', 'Preciso de ajuda', 'Por gentileza', 'Socorro'],
        'a': ['como montar o', 'onde baixo o manual do', 'estou com duvida no', 'veio faltando parafuso no', 'preciso de assistencia para'],
        'o': ['armario de cozinha', 'rack da sala', 'berco do bebe', 'esquema de montagem', 'manual da estante']
    },
    'trocas_devolucoes': {
        's': ['', 'Olá', 'Por favor', 'Gostaria de solicitar', 'Quero abrir'],
        'a': ['preciso trocar o', 'quero devolver a', 'como solicito o estorno do', 'desejo solicitar a troca da', 'como funciona a devolucao do'],
        'o': ['produto com defeito', 'mesa que veio arranhada', 'cadeira no prazo de 7 dias', 'pedido cancelado', 'item com avaria']
    },
    'reclamacoes': {
        's': ['', 'Urgente', 'Pessimo atendimento', 'Absurdo', 'Quero registrar'],
        'a': ['estou indignado com o', 'quero fazer uma queixa do', 'estou reclamando do', 'produto veio quebrado e o', 'atendimento horrivel do'],
        'o': ['atraso na minha entrega', 'servico de montagem', 'sac que nao responde', 'pos venda da loja', 'estado do meu movel']
    },
    'logistica_entregas': {
        's': ['', 'Olá', 'Bom dia', 'Por gentileza', 'Preciso saber'],
        'a': ['onde esta o meu', 'qual o prazo de entrega do', 'como rastreio a', 'qual a transportadora do', 'quando chega o'],
        'o': ['meu pedido', 'codigo de rastreamento', 'movel comprado', 'status do envio', 'agendamento da entrega']
    }
}

amostras = []
random.seed(42)

for intencao, comp in templates.items():
    for _ in range(20):
        s = random.choice(comp['s'])
        a = random.choice(comp['a'])
        o = random.choice(comp['o'])
        frase = f"{s} {a} {o}".strip().capitalize()
        amostras.append({
            'texto': frase,
            'intencao': intencao
        })

df_moveis = pd.DataFrame(amostras)

df_moveis.to_csv(
    'dataset_moveis_100.csv',
    index=False,
    encoding='utf-8'
)

print("Dataset criado com sucesso!")

Dataset criado com sucesso!


In [12]:
# Criar o Pipeline com TF-IDF + KNN
pipeline_knn = Pipeline([
    ('vectorizer', TfidfVectorizer()),
    ('classifier', KNeighborsClassifier(
        n_neighbors=3,
        metric='cosine'
    ))
])

# Treinar o modelo
pipeline_knn.fit(X_train, y_train)

print("Modelo KNN treinado com sucesso!")

Modelo KNN treinado com sucesso!


In [13]:
# Fazer previsões no conjunto de teste
y_pred = pipeline_knn.predict(X_test)

print("\n=== RELATÓRIO DE CLASSIFICAÇÃO - KNN ===")
print(classification_report(y_test, y_pred))

print("=== MATRIZ DE CONFUSÃO - KNN ===")
print(confusion_matrix(y_test, y_pred))


=== RELATÓRIO DE CLASSIFICAÇÃO - KNN ===
                    precision    recall  f1-score   support

logistica_entregas       1.00      1.00      1.00         6
       reclamacoes       1.00      1.00      1.00         6
           suporte       1.00      1.00      1.00         6
 trocas_devolucoes       1.00      1.00      1.00         6
            vendas       1.00      1.00      1.00         6

          accuracy                           1.00        30
         macro avg       1.00      1.00      1.00        30
      weighted avg       1.00      1.00      1.00        30

=== MATRIZ DE CONFUSÃO - KNN ===
[[6 0 0 0 0]
 [0 6 0 0 0]
 [0 0 6 0 0]
 [0 0 0 6 0]
 [0 0 0 0 6]]


In [6]:
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

# Carregar o dataset
df = pd.read_csv('dataset_moveis_100.csv')

# Separar textos e intenções
X = df['texto']
y = df['intencao']

# Dividir em treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

print("Dataset carregado com sucesso!")
print(f"Total de registros: {len(df)}")
print(f"Registros para treino: {len(X_train)}")
print(f"Registros para teste: {len(X_test)}")

Dataset carregado com sucesso!
Total de registros: 100
Registros para treino: 70
Registros para teste: 30


In [11]:
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# ============================================================
# 1. CARREGAR DATASET
# ============================================================

df = pd.read_csv('dataset_moveis_100.csv')

X = df['texto']
y = df['intencao']

# ============================================================
# 2. SEPARAR TREINO E TESTE
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

# ============================================================
# 3. CRIAR PIPELINE
# ============================================================

pipeline_tree = Pipeline([
    ('vectorizer', TfidfVectorizer()),
    ('classifier', DecisionTreeClassifier(random_state=42))
])

# ============================================================
# 4. TREINAR MODELO
# ============================================================

pipeline_tree.fit(X_train, y_train)

print("Decision Tree treinada com sucesso!")

# ============================================================
# 5. AVALIAÇÃO
# ============================================================

y_pred = pipeline_tree.predict(X_test)

print("\n=== MATRIZ DE CONFUSÃO - DECISION TREE ===")
print(confusion_matrix(y_test, y_pred))

print("\n=== RELATÓRIO DE CLASSIFICAÇÃO - DECISION TREE ===")
print(classification_report(y_test, y_pred))

# ============================================================
# 6. CONFIGURAÇÕES DO CHATBOT
# ============================================================

LIMIAR_CONFIANCA = 0.50

# Palavras relacionadas ao contexto do SAC
PALAVRAS_VALIDAS = [
    'comprar', 'preco', 'preço', 'cupom', 'adquirir', 'orcamento',
    'orçamento', 'sofa', 'sofá', 'mesa', 'jantar', 'guarda', 'roupa',
    'painel', 'tv', 'colchao', 'colchão',

    'montar', 'montagem', 'manual', 'duvida', 'dúvida',
    'parafuso', 'assistencia', 'assistência', 'armario', 'armário',
    'rack', 'berco', 'berço', 'estante',

    'trocar', 'troca', 'devolver', 'devolucao', 'devolução',
    'estorno', 'defeito', 'arranhada', 'avaria', 'cancelado',

    'indignado', 'queixa', 'reclamando', 'reclamação', 'reclamacao',
    'quebrado', 'horrivel', 'horrível', 'atendimento', 'sac',

    'pedido', 'entrega', 'entrega', 'rastreio', 'rastreamento',
    'transportadora', 'chega', 'envio', 'status', 'agendamento',
    'prazo', 'móvel', 'movel'
]

# ============================================================
# 7. FUNÇÃO DE CLASSIFICAÇÃO
# ============================================================

def classificar_mensagem(frase):

    frase_lower = frase.lower()

    # Verificar se existem palavras relacionadas ao domínio
    possui_contexto = any(
        palavra in frase_lower
        for palavra in PALAVRAS_VALIDAS
    )

    # Se não houver nenhuma palavra relacionada ao SAC,
    # encaminha diretamente para atendimento humano.
    if not possui_contexto:
        print("Desculpe, não entendi sua solicitação. Encaminhando você para um atendente humano...")
        return

    # Fazer previsão
    probs = pipeline_tree.predict_proba([frase])

    maior_prob = np.max(probs)

    intencao = pipeline_tree.predict([frase])[0]

    # Verificar limiar de confiança
    if maior_prob >= LIMIAR_CONFIANCA:

        print(f"Intenção identificada: {intencao}")
        print(f"Probabilidade: {maior_prob:.2%}")

    else:

        print("Desculpe, não entendi sua solicitação. Encaminhando você para um atendente humano...")


# ============================================================
# 8. TESTES MANUAIS
# ============================================================

print("\n=== INICIANDO BATERIA DE TESTES (8 INPUTS OBRIGATÓRIOS) ===")

for i in range(1, 9):

    print(f"\n[Teste {i}/8]")

    frase = input("Digite a frase do cliente: ").strip()

    classificar_mensagem(frase)

Decision Tree treinada com sucesso!

=== MATRIZ DE CONFUSÃO - DECISION TREE ===
[[4 0 0 0 2]
 [1 4 1 0 0]
 [0 0 6 0 0]
 [0 0 1 5 0]
 [0 0 0 1 5]]

=== RELATÓRIO DE CLASSIFICAÇÃO - DECISION TREE ===
                    precision    recall  f1-score   support

logistica_entregas       0.80      0.67      0.73         6
       reclamacoes       1.00      0.67      0.80         6
           suporte       0.75      1.00      0.86         6
 trocas_devolucoes       0.83      0.83      0.83         6
            vendas       0.71      0.83      0.77         6

          accuracy                           0.80        30
         macro avg       0.82      0.80      0.80        30
      weighted avg       0.82      0.80      0.80        30


=== INICIANDO BATERIA DE TESTES (8 INPUTS OBRIGATÓRIOS) ===

[Teste 1/8]
Digite a frase do cliente: Quero comprar um guarda roupa
Intenção identificada: trocas_devolucoes
Probabilidade: 100.00%

[Teste 2/8]
Digite a frase do cliente: asdasdasdasd
Desculpe, n